---
driver:
  name: vagrant
  network:
    - ["forwarded_port", { guest: 3000, host: 3000 }]
    - ["private_network", { ip: "192.168.33.10" }]

provisioner:
    name: chef_zero
    require_chef_omnibus: 12.7.2

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: "<%= ENV['KNIFE_HOME'] %>/data_bags"
    encrypted_data_bag_secret_key_path: "<%= ENV['HOME'] %>/.chef/cml/secret.pem"
    attributes: ~
