name 'samson'
maintainer 'Jonathan Serafini'
maintainer_email 'jonathan@serafini.ca'
license 'apachev2'
description 'Installs/Configures samson'
long_description 'Installs/Configures samson'
version '0.1.0'
depends 'common_deploy',  '~> 0.2.0'
depends 'nvm',            '~> 0.1.7'
depends 'ruby_rbenv',     '~> 1.0.0'
depends 'ruby_build',     '~> 1.0.0'
